import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import { GetServerSideProps, NextPage } from "next";
import axios from "axios";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

type Props = {
  items: {
    name: string,
    email: string,
    description: string,
    time: Date,
    claimed: Boolean
  }
}

const Home: NextPage<Props> = ({items}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        
        hi
      </div>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  // get list of food items nearby

  try {
    const res = await axios.get("http://localhost:3000/api/test") //update to post later with location
    const items = res.data
    return {
      props: {
        items
      }
    }
  } catch (err) {
    return {
      notFound: true
    }
  }
}

export default Home;