import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import { GetServerSideProps, NextPage } from "next";
import axios from "axios";
import { Button, Flex, Text } from "@chakra-ui/react";
import Item from "@/types/Item";
import { useEffect } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

type Props = {
  items: Item[]
}


const Home: NextPage<Props> = ({items}) => {
  useEffect(() => {
    console.log(items)
  }, [items])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <Flex justifyContent={'space-around'} alignItems={'center'}  w={'100vw'} h={'100vh'}>
        {items.map((item) => (
          <Flex flexDir={'column'} bgColor={'red'} w={'25vw'} alignItems={'center'}>
            <Text>{item.name}</Text>
            <Image src={item.image} width={100} height={100} alt={"food pic"}/>        
            <Text size={'sm'}>{item.description}</Text>
            <Button>Claim!</Button>
            <Text>{item.points}</Text>
            <Text>{new Date(item.time).toDateString()}</Text>
            <Text>{item.account.name}</Text>
          </Flex>          
        ))}
        </Flex>
        
      
    </>
  );
}

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  // get list of food items nearby

  try {
    const res = await axios.get("http://localhost:3000/api/test") //update to post later with location
    const items: Item[] = res.data
    return {
      props: {
        items
      }        
    }
  } catch (err) {
    return {
      notFound: true
    }
  }
}

export default Home;